name: work-1

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - '**/*.txt'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - '.prettier*'
      - '.vscode/**'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  makeTagAndRelease:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          draft: false
          prerelease: false

  buildImageAndPush:
    name: 도커 이미지 빌드와 푸시
    needs: makeTagAndRelease
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: deploy
    steps:
      - uses: actions/checkout@v4

      - name: Docker Buildx 설치
        uses: docker/setup-buildx-action@v2

      - name: GHCR 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 소문자 owner를 스텝 출력으로 만들어서 이후 표현식에서 안전하게 사용
      - name: Set lowercase owner
        id: owner
        shell: bash
        run: |
          echo "owner_lc=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.owner.outputs.owner_lc }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ needs.makeTagAndRelease.outputs.tag_name }}
            type=raw,value=latest

      - name: 빌드 앤 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
